#!/usr/bin/env python3
"""Emit C for the functions of one funcs.toml module.

Output: <out>/<module>.c and <out>/<module>.h. One C function per
(routine, entry state), one labelled block per instruction.
Unimplemented (opcode, width) combinations are fatal.
"""
from __future__ import annotations

import argparse
import os
import sys
import tomllib

import decode
import funcs
from decode import DecodeError, Insn

HEADER = '/* generated by recomp/emit.py from funcs.toml; do not edit */'


class EmitError(Exception):
    pass


def _dp(i: Insn) -> str:
    return f'0x{i.operand:02X}'


def _abs(i: Insn) -> str:
    return f'0x{i.operand:04X}'


def _long(i: Insn) -> str:
    return f'0x{i.operand:06X}'


def _imm(i: Insn) -> str:
    return f'0x{i.operand:0{2 if i.size == 2 else 4}X}'


def _at(i: Insn) -> str:
    return f'0x{i.addr:06X}'


def _branch(cond: str):
    def f(i: Insn) -> list[str]:
        tgt = f'goto L_{i.branch_target():06X};'
        return [tgt] if not cond else [f'if ({cond}) {tgt}']
    return f


# ---- template generation ----
# (opcode, width) -> body lines. width: '8'/'16' for M/X-sized ops, '' otherwise.

# mode -> (effective-address expression, 16-bit access wraps in bank 0)
_EA = {
    'dp':            (lambda i: f'ea_dp(cpu, {_dp(i)})', True),
    'dp_x':          (lambda i: f'ea_dp_x(cpu, {_dp(i)})', True),
    'dp_y':          (lambda i: f'ea_dp_y(cpu, {_dp(i)})', True),
    'sr':            (lambda i: f'ea_sr(cpu, {_dp(i)})', True),
    'abs':           (lambda i: f'ea_abs(cpu, {_abs(i)})', False),
    'abs_x':         (lambda i: f'ea_abs_x(cpu, {_abs(i)})', False),
    'abs_y':         (lambda i: f'ea_abs_y(cpu, {_abs(i)})', False),
    'long':          (lambda i: _long(i), False),
    'long_x':        (lambda i: f'ea_long_x(cpu, {_long(i)})', False),
    'dp_ind':        (lambda i: f'ea_dp_ind(cpu, {_dp(i)})', False),
    'dp_x_ind':      (lambda i: f'ea_dp_x_ind(cpu, {_dp(i)})', False),
    'dp_ind_y':      (lambda i: f'ea_dp_ind_y(cpu, {_dp(i)})', False),
    'dp_ind_long':   (lambda i: f'ea_dp_ind_long(cpu, {_dp(i)})', False),
    'dp_ind_long_y': (lambda i: f'ea_dp_ind_long_y(cpu, {_dp(i)})', False),
    'sr_ind_y':      (lambda i: f'ea_sr_ind_y(cpu, {_dp(i)})', False),
}


def _rd(expr: str, w: str, b0: bool) -> str:
    if w == '8':
        return f'read8({expr})'
    return f'read16_b0({expr})' if b0 else f'read16({expr})'


def _wr(expr: str, w: str, b0: bool, val: str) -> str:
    if w == '8':
        return f'write8({expr}, {val});'
    return f'write16_b0({expr}, {val});' if b0 else f'write16({expr}, {val});'


def _wr_rmw(expr: str, w: str, b0: bool, val: str) -> str:
    """A read-modify-write's write: 16-bit ones write the high byte first."""
    if w == '8':
        return f'write8({expr}, {val});'
    return f'write16_b0_rmw({expr}, {val});' if b0 else f'write16_rmw({expr}, {val});'


def _reg(name: str, w: str) -> str:
    """Register value at width w."""
    if name == 'A':
        return 'a8(cpu)' if w == '8' else 'cpu->A'
    return f'(uint8_t)cpu->{name}' if w == '8' else f'cpu->{name}'


def _value(i: Insn, w: str) -> str:
    if i.mode in ('imm_m', 'imm_x'):
        return _imm(i)
    ea, b0 = _EA[i.mode]
    return _rd(ea(i), w, b0)


_LOADS = {'LDA': 'lda', 'LDX': 'ldx', 'LDY': 'ldy', 'ORA': 'ora', 'AND': 'and', 'EOR': 'eor'}
_STORES = {'STA': 'cpu->A', 'STX': 'cpu->X', 'STY': 'cpu->Y', 'STZ': '0'}
_RMW = {'INC': 'inc', 'DEC': 'dec', 'ASL': 'asl', 'LSR': 'lsr', 'ROL': 'rol', 'ROR': 'ror',
        'TSB': 'tsb', 'TRB': 'trb'}
_FLAGS = {'CLC': 'cpu->c = 0;', 'SEC': 'cpu->c = 1;', 'CLI': 'cpu->i = 0;', 'SEI': 'cpu->i = 1;',
          'CLD': 'cpu->d = 0;', 'SED': 'cpu->d = 1;', 'CLV': 'cpu->v = 0;'}
_BRANCH = {'BPL': '!cpu->n', 'BMI': 'cpu->n', 'BVC': '!cpu->v', 'BVS': 'cpu->v',
           'BCC': '!cpu->c', 'BCS': 'cpu->c', 'BNE': '!cpu->z', 'BEQ': 'cpu->z',
           'BRA': '', 'BRL': ''}
# transfer -> (dest register, source expression at 16 bits, width source)
_XFER = {'TAX': ('X', 'cpu->A'), 'TAY': ('Y', 'cpu->A'), 'TXA': ('A', 'cpu->X'),
         'TYA': ('A', 'cpu->Y'), 'TXY': ('Y', 'cpu->X'), 'TYX': ('X', 'cpu->Y'),
         'TSX': ('X', 'cpu->S')}


def _set_reg(name: str, w: str, val16: str) -> list[str]:
    if name == 'A':
        if w == '8':
            return [f'set_a8(cpu, (uint8_t){val16});', 'set_nz8(cpu, a8(cpu));']
        return [f'cpu->A = {val16};', 'set_nz16(cpu, cpu->A);']
    if w == '8':
        return [f'cpu->{name} = (uint8_t){val16};', f'set_nz8(cpu, (uint8_t)cpu->{name});']
    return [f'cpu->{name} = {val16};', f'set_nz16(cpu, cpu->{name});']


def _generate(mn: str, md: str, w: str):
    """Template for one (mnemonic, mode, width), or None."""
    if mn in _LOADS and (md in _EA or md in ('imm_m', 'imm_x')):
        return lambda i: [f'{_LOADS[mn]}{w}(cpu, {_value(i, w)});']
    if mn in ('ADC', 'SBC') and (md in _EA or md == 'imm_m'):
        return lambda i: [f'{mn.lower()}{w}(cpu, {_value(i, w)}, {_at(i)});']
    if mn in ('CMP', 'CPX', 'CPY') and (md in _EA or md in ('imm_m', 'imm_x')):
        reg = {'CMP': 'A', 'CPX': 'X', 'CPY': 'Y'}[mn]
        return lambda i: [f'cmp{w}(cpu, {_reg(reg, w)}, {_value(i, w)});']
    if mn == 'BIT' and (md in _EA or md == 'imm_m'):
        return lambda i: [f'bit{w}(cpu, {_value(i, w)}, {int(md == "imm_m")});']
    if mn in _STORES and md in _EA:
        ea, b0 = _EA[md]
        src = _STORES[mn]
        val = src if src == '0' else _reg(src[5:], w)
        return lambda i: [_wr(ea(i), w, b0, val)]
    if mn in _RMW and md in _EA:
        ea, b0 = _EA[md]
        return lambda i: [f'uint32_t ea = {ea(i)};',
                          _wr_rmw('ea', w, b0, f'{_RMW[mn]}{w}(cpu, {_rd("ea", w, b0)})')]
    if mn in _RMW and md == 'A':
        if w == '8':
            return lambda i: [f'set_a8(cpu, {_RMW[mn]}8(cpu, a8(cpu)));']
        return lambda i: [f'cpu->A = {_RMW[mn]}16(cpu, cpu->A);']
    if mn in _FLAGS:
        return lambda i: [_FLAGS[mn]]
    if mn in _BRANCH:
        return _branch(_BRANCH[mn])
    if mn in _XFER:
        dst, src = _XFER[mn]
        return lambda i: _set_reg(dst, w, src)
    if mn in ('INX', 'INY', 'DEX', 'DEY'):
        reg = mn[2]
        op = '+' if mn.startswith('IN') else '-'
        return lambda i: _set_reg(reg, w, f'(uint16_t)(cpu->{reg} {op} 1)')
    if mn in ('PHA', 'PHX', 'PHY'):
        reg = mn[2]
        if w == '8':
            return lambda i: [f'push8(cpu, (uint8_t)cpu->{reg});']
        return lambda i: [f'push16(cpu, cpu->{reg});']
    if mn in ('PLA', 'PLX', 'PLY'):
        reg = mn[2]
        return lambda i: _set_reg(reg, w, 'pull8(cpu)' if w == '8' else 'pull16(cpu)')
    return None


_SPECIAL = {
    (0x08, ''):   lambda i: ['push8(cpu, get_p(cpu));'],                                   # PHP
    (0x28, ''):   lambda i: ['set_p(cpu, pull8(cpu));'],                                   # PLP
    (0x60, ''):   lambda i: ['op_rts(cpu);', 'return;'],                                   # RTS
    (0x6B, ''):   lambda i: ['op_rtl(cpu);', 'return;'],                                   # RTL
    (0x7B, ''):   lambda i: ['op_tdc(cpu);'],                                              # TDC
    (0x5B, ''):   lambda i: ['cpu->DP = cpu->A;', 'set_nz16(cpu, cpu->DP);'],              # TCD
    (0x1B, ''):   lambda i: ['cpu->S = cpu->A;'],                                          # TCS
    (0x3B, ''):   lambda i: ['cpu->A = cpu->S;', 'set_nz16(cpu, cpu->A);'],                # TSC
    (0x9A, ''):   lambda i: ['cpu->S = cpu->X;'],                                          # TXS
    (0xEB, ''):   lambda i: ['cpu->A = (uint16_t)(cpu->A >> 8 | cpu->A << 8);',            # XBA
                             'set_nz8(cpu, a8(cpu));'],
    (0x8B, ''):   lambda i: ['push8(cpu, cpu->DB);'],                                      # PHB
    (0xAB, ''):   lambda i: ['cpu->DB = pull8(cpu);', 'set_nz8(cpu, cpu->DB);'],           # PLB
    (0x0B, ''):   lambda i: ['push16(cpu, cpu->DP);'],                                     # PHD
    (0x2B, ''):   lambda i: ['cpu->DP = pull16(cpu);', 'set_nz16(cpu, cpu->DP);'],         # PLD
    (0x4B, ''):   lambda i: [f'push8(cpu, 0x{i.addr >> 16:02X});'],                        # PHK
    (0xF4, ''):   lambda i: [f'push16(cpu, {_abs(i)});'],                                  # PEA
    (0xD4, ''):   lambda i: [f'push16(cpu, read16_b0(ea_dp(cpu, {_dp(i)})));'],            # PEI
    (0x62, ''):   lambda i: [f'push16(cpu, 0x{i.branch_target() & 0xFFFF:04X});'],        # PER
    (0xC2, ''):   lambda i: [f'op_rep(cpu, 0x{i.operand:02X});'],                          # REP
    (0xE2, ''):   lambda i: [f'op_sep(cpu, 0x{i.operand:02X});'],                          # SEP
    (0xEA, ''):   lambda i: [';'],                                                         # NOP
    (0xFB, ''):   lambda i: ['op_xce(cpu);'],                                              # XCE
    # Crash traps / interrupt waits: no model in v0, fail at the address.
    (0x00, ''):   lambda i: [f'ct_fatal("${i.addr:06X}: BRK executed");'],
    (0x02, ''):   lambda i: [f'ct_fatal("${i.addr:06X}: COP executed");'],
    (0xDB, ''):   lambda i: [f'ct_fatal("${i.addr:06X}: STP executed");'],
    (0xCB, ''):   lambda i: [f'ct_fatal("${i.addr:06X}: WAI executed");'],
    (0x54, '16'): lambda i: [f'mvn16(cpu, 0x{i.addr:06X}, 0x{i.operand & 0xFF:02X}, 0x{i.operand >> 8:02X});'],  # MVN
}


def _build_templates() -> dict:
    out = dict(_SPECIAL)
    special_ops = {op for op, _ in _SPECIAL}
    for op, (mn, md) in decode.OPCODES.items():
        if op in special_ops:
            continue
        dep = decode.width_dependency(mn, md)
        for w in (['8', '16'] if dep else ['']):
            f = _generate(mn, md, w)
            if f is not None:
                out[(op, w)] = f
    return out


TEMPLATES = _build_templates()

NO_FALLTHROUGH = {'RTS', 'RTL', 'RTI', 'BRA', 'BRL', 'JMP', 'JML', 'STP', 'BRK', 'COP', 'WAI'}  # JMP includes (abs,X)


def implemented_opcodes() -> set[int]:
    return {op for op, _ in TEMPLATES} | {0x20, 0x22, 0x4C, 0x5C, 0x7C, 0xFC}   # emit_function


_OVERLAY = ''   # set while emitting an overlay: names its WRAM functions


def c_name(addr: int, st: decode.State) -> str:
    if _OVERLAY and addr >> 16 in (0x7E, 0x7F):
        return f'f_{_OVERLAY}_{addr:06X}_{st.tag()}'
    return f'f_{addr:06X}_{st.tag()}'


_EXTERNS: dict = {}


_REG = None           # the registry being emitted from (for _via_dispatch)
_HOOK_MEMO: dict = {}


def _strict_rest(i: Insn) -> str:
    """Without the frame scheduler (diff_all), code that isn't compiled is
    run by the strict interpreter, the same oracle generated code is compared
    against: hand it the rest of the function from this instruction, so the
    oracle's own checks (call returns, table bounds) apply to it alike."""
    return (f'if (!ct_exec_hook) {{ cpu->PB = 0x{i.addr >> 16:02X}; cpu->PC = 0x{i.addr & 0xFFFF:04X}; '
            'ct_interp_rest(cpu, s0); return; }')


def _via_dispatch(target: int, cst: decode.State) -> bool:
    """A compiled callee that can reach a hook standing in for code
    (calls_extern): the frame scheduler never runs it natively, so a call to
    it from compiled code goes through the dispatcher there too (the hook
    would stand in for code the scheduler does run)."""
    return _REG is not None and target not in _EXTERNS and \
        calls_extern(_REG, target, cst, _HOOK_MEMO)


def takes_hook(fn: decode.Function, externs: dict) -> bool:
    """Does fn itself take a hook even in the scheduler: a call or jump to a
    noreturn extern, or an extern in a jump table's cases?"""
    direct = [t for t, _ in list(fn.calls.values()) + list(fn.tails.values())]
    return any(t in externs and externs[t].noreturn for t in direct) or \
        any(t in externs for ts, _ in fn.tables.values() for t in ts)


def _routed(target: int) -> bool:
    """An extern whose real code runs in the frame scheduler (extern_call,
    extern_tail): one that returns. A noreturn one (a stack switch, a jump
    into a program) keeps its hook everywhere, and what can reach it stays
    interpreted there (calls_extern)."""
    ext = _EXTERNS.get(target)
    return ext is not None and not ext.noreturn


def extern_call(target: int, cst: decode.State, back: int, n: int, check: str) -> list[str]:
    """A call to an [[extern]] boundary, return address pushed. In the frame
    scheduler the real code runs (the dispatcher: interpreted, or native
    where compiled); elsewhere (diff_all and its strict interpreter) the hook
    stands in for it, as before."""
    cond = [f'!ct_call_interp(cpu, 0x{target:06X}, 0x{back:06X}, {n})']
    cond += [f'cpu->{r} != {int(v)}' for r, v in (('m', cst.m), ('x', cst.x)) if v is not None]
    return ['if (ct_exec_hook) {',
            f'    if ({" || ".join(cond)}) {{ ct_interp_rest(cpu, s0); return; }}',
            '} else {',
            f'    ct_run(cpu, {callee(target, cst)});',
            f'    {check}',
            '}']


def extern_tail(target: int, cst: decode.State) -> list[str]:
    """A jump to an [[extern]] boundary: the real code in the scheduler (its
    return is this function's), the hook elsewhere."""
    return ['if (ct_exec_hook) {',
            f'    cpu->PB = 0x{target >> 16:02X};',
            f'    cpu->PC = 0x{target & 0xFFFF:04X};',
            '    ct_interp_rest(cpu, s0);',
            '    return;',
            '}',
            f'ct_tail(cpu, {callee(target, cst)});', 'return;']


def callee(target: int, st: decode.State) -> str:
    ext = _EXTERNS.get(target)
    return f'ct_hook_{ext.hook}' if ext else c_name(target, st)


def return_check(site: int, cond: str, fatal: str, args: str) -> str:
    """A compiled callee that ends somewhere other than the call site's
    return address is a non-local return (the game's RTS-as-jump tricks) or
    a handed-off rest that ran past its frame. With the frame scheduler,
    hand this function's rest to the interpreter and unwind the native
    frames to the dispatcher, which continues from the CPU's own PB:PC
    (the interpreter is the oracle for real runs). Without one (the strict
    diff_all harness), fail exactly like the interpreter does."""
    return (f'if ({cond}) {{ if (ct_exec_hook) {{ ct_tail_rest(cpu, s0); return; }} '
            f'ct_fatal({fatal}, {args}); }}')


def emit_function(fm: funcs.FuncMeta, fn: decode.Function) -> list[str]:
    st = fn.state
    lines = [
        f'/* ${fm.addr:06X} {fm.name}: {fn.size} bytes, entry {st.tag()} e{int(st.e)} */',
        f'void {c_name(fm.addr, st)}(CPU *cpu)',
        '{',
        f'    cpu_enter(cpu, 0x{fm.addr:06X}, {int(st.m)}, {int(st.x)});',
    ]
    ext_edges = [t for t, c in list(fn.calls.values()) + list(fn.tails.values())
                 if _routed(t) or _via_dispatch(t, c)]
    ext_edges += [t for ts, c in fn.tables.values() for t in ts if _via_dispatch(t, c)]
    if (fn.interp_calls or fn.dyn_tables or fn.interp_tails or fn.table_interp or ext_edges
            or fn.calls or fn.tables):
        lines.append('    const uint16_t s0 = cpu->S;   /* the return address sits above */')
    keys = {i.key for i in fn.insns}
    per_addr: dict[int, int] = {}
    for i in fn.insns:
        per_addr[i.addr] = per_addr.get(i.addr, 0) + 1

    def label(addr: int, key: tuple) -> str:
        if (addr,) + key not in keys:
            raise EmitError(f'${addr:06X} ({decode.State(*key).tag()}): jump target not decoded')
        if per_addr[addr] == 1:
            return f'L_{addr:06X}'
        return f'L_{addr:06X}_{decode.State(*key).tag()}'

    entry = (fm.addr,) + st.key()
    if fn.insns[0].key != entry:
        lines.append(f'    goto {label(fm.addr, st.key())};')

    for k, i in enumerate(fn.insns):
        nxt = fn.insns[k + 1] if k + 1 < len(fn.insns) else None
        post = fn.post[i.key]
        try:
            w = i.width()
        except DecodeError as ex:
            raise EmitError(str(ex)) from None
        t = TEMPLATES.get((i.opcode, w))

        if i.opcode in (0xFC, 0x7C) and i.key in fn.dyn_tables:
            cst = fn.dyn_tables[i.key]
            bank = i.addr >> 16
            ret = (i.addr + 2) & 0xFFFF

            def t(i, cst=cst, bank=bank, ret=ret):
                # a table of unknown length: read the target as the CPU does
                # (bus reads, after a JSR's pushes: the cycle model charges
                # them at the table's own speed) and let the dispatcher run it
                body = [f'uint16_t p = (uint16_t)(0x{i.operand:04X} + cpu->X);',
                        f'uint32_t t = read8(0x{bank:02X}0000u | p);',
                        f't = 0x{bank:02X}0000u | t | (uint32_t)read8(0x{bank:02X}0000u | '
                        f'(uint16_t)(p + 1)) << 8;']
                if i.opcode == 0x7C:
                    return [_strict_rest(i)] + body + ['cpu->PC = (uint16_t)t;',
                                                       'ct_interp_rest(cpu, s0);', 'return;']
                back = (bank << 16) | ((ret + 1) & 0xFFFF)
                cond = [f'!ct_call_interp(cpu, t, 0x{back:06X}, 2)']
                cond += [f'cpu->{r} != {int(v)}' for r, v in (('m', cst.m), ('x', cst.x))
                         if v is not None]
                return [_strict_rest(i), f'push16(cpu, 0x{ret:04X});'] + body + \
                    [f'if ({" || ".join(cond)}) {{ ct_interp_rest(cpu, s0); return; }}']
        elif i.opcode in (0x20, 0x22) and i.key in fn.interp_calls:
            target, cst = fn.interp_calls[i.key]
            long = i.opcode == 0x22
            ret = (i.addr + (3 if long else 2)) & 0xFFFF
            bank = i.addr >> 16
            back = (bank << 16) | ((ret + 1) & 0xFFFF)

            def t(i, target=target, cst=cst, ret=ret, bank=bank, long=long, back=back):
                body = [_strict_rest(i)] + ([f'push8(cpu, 0x{bank:02X});'] if long else [])
                body.append(f'push16(cpu, 0x{ret:04X});')
                # came back elsewhere, or in another M/X state: interpret the rest
                cond = [f'!ct_call_interp(cpu, 0x{target:06X}, 0x{back:06X}, {3 if long else 2})']
                cond += [f'cpu->{r} != {int(v)}' for r, v in (('m', cst.m), ('x', cst.x))
                         if v is not None]
                body.append(f'if ({" || ".join(cond)}) {{ ct_interp_rest(cpu, s0); return; }}')
                return body
        elif i.opcode == 0x20 and i.key in fn.calls:
            target, cst = fn.calls[i.key]
            ret = (i.addr + 2) & 0xFFFF
            chk = return_check(
                i.addr, f'cpu->PC != 0x{(ret + 1) & 0xFFFF:04X}',
                '"$%06X: callee returned to $%04X, expected $%04X"',
                f'0x{i.addr:06X}, cpu->PC, 0x{(ret + 1) & 0xFFFF:04X}')
            if _routed(target) or _via_dispatch(target, cst):
                back = (i.addr & 0xFF0000) | ((ret + 1) & 0xFFFF)
                t = lambda i, target=target, cst=cst, ret=ret, back=back, chk=chk: \
                    [f'push16(cpu, 0x{ret:04X});'] + extern_call(target, cst, back, 2, chk)
            else:
                t = lambda i, target=target, cst=cst, ret=ret, chk=chk: [
                    f'push16(cpu, 0x{ret:04X});', f'ct_run(cpu, {callee(target, cst)});', chk]
        elif i.opcode == 0x22 and i.key in fn.calls:
            target, cst = fn.calls[i.key]
            ret = (i.addr + 3) & 0xFFFF
            bank = i.addr >> 16
            chk = return_check(
                i.addr, f'cpu->PC != 0x{(ret + 1) & 0xFFFF:04X} || cpu->PB != 0x{bank:02X}',
                '"$%06X: callee returned to $%02X%04X, expected $%06X"',
                f'0x{i.addr:06X}, cpu->PB, cpu->PC, 0x{bank:02X}{(ret + 1) & 0xFFFF:04X}')
            if _routed(target) or _via_dispatch(target, cst):
                back = (bank << 16) | ((ret + 1) & 0xFFFF)
                t = lambda i, target=target, cst=cst, ret=ret, bank=bank, back=back, chk=chk: [
                    f'push8(cpu, 0x{bank:02X});', f'push16(cpu, 0x{ret:04X});',
                    f'cpu->PB = 0x{target >> 16:02X};'] + extern_call(target, cst, back, 3, chk)
            else:
                t = lambda i, target=target, cst=cst, ret=ret, bank=bank, chk=chk: [
                    f'push8(cpu, 0x{bank:02X});',
                    f'push16(cpu, 0x{ret:04X});',
                    f'cpu->PB = 0x{target >> 16:02X};',
                    f'ct_run(cpu, {callee(target, cst)});', chk]
        elif i.opcode in (0x7C, 0xFC) and i.key in fn.tables:
            targets, cst = fn.tables[i.key]
            is_call = i.opcode == 0xFC
            ret = (i.addr + 2) & 0xFFFF

            interp = fn.table_interp.get(i.key, set())
            back = (i.addr & 0xFF0000) | ((ret + 1) & 0xFFFF)

            def t(i, targets=targets, cst=cst, is_call=is_call, ret=ret, interp=interp, back=back):
                body = [_strict_rest(i)] if interp else []   # uncompiled cases: see _strict_rest
                body += [f'push16(cpu, 0x{ret:04X});'] if is_call else []
                body.append('switch (cpu->X) {')
                after = 'break;' if is_call else 'return;'
                mx = [f'cpu->{r} != {int(v)}' for r, v in (('m', cst.m), ('x', cst.x))
                      if v is not None]
                for n, tg in enumerate(targets):
                    if tg in interp and is_call:   # run through the interpreter's dispatch
                        cond = ' || '.join([f'!ct_call_interp(cpu, 0x{tg:06X}, 0x{back:06X}, 2)'] + mx)
                        body.append(f'case 0x{2 * n:04X}: if ({cond}) {{ ct_interp_rest(cpu, s0); '
                                    'return; } break;')
                    elif tg in interp:
                        body.append(f'case 0x{2 * n:04X}: cpu->PC = 0x{tg & 0xFFFF:04X}; '
                                    'ct_interp_rest(cpu, s0); return;')
                    elif _via_dispatch(tg, cst) and is_call:
                        cond = ' || '.join([f'!ct_call_interp(cpu, 0x{tg:06X}, 0x{back:06X}, 2)'] + mx)
                        body.append(f'case 0x{2 * n:04X}: if (ct_exec_hook) {{ if ({cond}) {{ '
                                    f'ct_interp_rest(cpu, s0); return; }} }} else ct_run(cpu, {callee(tg, cst)}); '
                                    'break;')
                    elif _via_dispatch(tg, cst):
                        body.append(f'case 0x{2 * n:04X}: if (ct_exec_hook) {{ cpu->PC = 0x{tg & 0xFFFF:04X}; '
                                    f'ct_interp_rest(cpu, s0); return; }} ct_tail(cpu, {callee(tg, cst)}); return;')
                    elif is_call:
                        body.append(f'case 0x{2 * n:04X}: ct_run(cpu, {callee(tg, cst)}); break;')
                    else:
                        body.append(f'case 0x{2 * n:04X}: ct_tail(cpu, {callee(tg, cst)}); return;')
                body.append(f'default: ct_fatal("${i.addr:06X}: jump table index $%04X out of range", '
                            'cpu->X);')
                body.append('}')
                if is_call:
                    body.append(return_check(
                        i.addr, f'cpu->PC != 0x{(ret + 1) & 0xFFFF:04X}',
                        '"$%06X: callee returned to $%04X, expected $%04X"',
                        f'0x{i.addr:06X}, cpu->PC, 0x{(ret + 1) & 0xFFFF:04X}'))
                return body
        elif i.opcode == 0x5C and i.key in fn.interp_tails:
            target, cst = fn.interp_tails[i.key]
            t = lambda i, target=target: [f'cpu->PB = 0x{target >> 16:02X};',
                                          f'cpu->PC = 0x{target & 0xFFFF:04X};',
                                          'ct_interp_rest(cpu, s0);   /* its return is ours */',
                                          'return;']
        elif i.opcode == 0x5C and i.key in fn.tails:
            target, cst = fn.tails[i.key]
            if _routed(target) or _via_dispatch(target, cst):
                t = lambda i, target=target, cst=cst: [f'cpu->PB = 0x{target >> 16:02X};'] + \
                    extern_tail(target, cst)
            else:
                t = lambda i, target=target, cst=cst: [f'cpu->PB = 0x{target >> 16:02X};',
                                                       f'ct_tail(cpu, {callee(target, cst)});',
                                                       'return;']
        elif i.opcode == 0x4C:
            if i.key in fn.tails:
                target, cst = fn.tails[i.key]
                if _routed(target) or _via_dispatch(target, cst):
                    t = lambda i, target=target, cst=cst: extern_tail(target, cst)
                else:
                    t = lambda i, target=target, cst=cst: [f'ct_tail(cpu, {callee(target, cst)});',
                                                           'return;']
            else:
                tgt = (i.addr & 0xFF0000) | i.operand
                dest = label(tgt, post)
                tick = f'ct_loop(0x{i.addr:06X}); ' if tgt <= i.addr else ''
                t = lambda i, dest=dest, tick=tick: [f'{tick}goto {dest};']
        elif i.mnemonic in _BRANCH:
            tgt = i.branch_target()
            dest = label(tgt, post)
            cond = _BRANCH[i.mnemonic]
            tick = f'ct_loop(0x{i.addr:06X}); ' if tgt <= i.addr else ''
            if i.mnemonic != 'BRL':
                tick = 'ct_cyc_taken = 1; ' + tick   # cycle model: taken branch (not BRL)
            if cond:
                t = lambda i, dest=dest, cond=cond, tick=tick: [f'if ({cond}) {{ {tick}goto {dest}; }}']
            else:
                t = lambda i, dest=dest, tick=tick: [f'{tick}goto {dest};']
        if i.opcode == 0x40:   # RTI: interrupt handlers (entered through their vectors)
            t = lambda i: [f'op_rti(cpu, 0x{i.addr:06X});', 'return;']
        if t is None:
            raise EmitError(f'${i.addr:06X}: {i.text()} (opcode ${i.opcode:02X}, '
                            f'width {w or "-"}) not implemented')
        body = t(i)
        if i.mnemonic == 'PLP':
            if post[0] is None or post[1] is None:
                raise EmitError(f'${i.addr:06X}: PLP restores unknown M/X')
            body.append(f'cpu_check_mx(cpu, 0x{i.addr:06X}, {int(post[0])}, {int(post[1])});')
        if i.key in fn.call_exits and not fn.call_exits[i.key]:
            if 'ct_call_interp' in '\n'.join(body):
                # the real code ran and came back anyway: go on interpreted
                body.append('if (ct_exec_hook) { ct_interp_rest(cpu, s0); return; }')
            body.append(f'ct_fatal("${i.addr:06X}: callee does not return");')
        elif i.key in fn.call_exits:
            for k in fn.call_exits[i.key]:
                body.append(f'if (cpu->m == {int(k[0])} && cpu->x == {int(k[1])}) '
                            f'goto {label(i.next_addr, k)};')
            body.append(f'ct_fatal("${i.addr:06X}: callee returned with m%d x%d", cpu->m, cpu->x);')
        elif i.mnemonic not in NO_FALLTHROUGH:
            succ = (i.next_addr,) + post
            if nxt is None or nxt.key != succ:
                body.append(f'goto {label(i.next_addr, post)};')
        lines.append(f'{label(i.addr, i.key[1:])}: /* {i.text()} */')
        last = i.opcode if i.size == 1 else (i.operand >> (8 * (i.size - 2))) & 0xFF
        lines.append(f'    ct_insn(cpu, 0x{i.addr:06X}, 0x{i.opcode:02X}, 0x{last:02X});')
        if len(body) == 1:
            lines.append(f'    {{ {body[0]} }}')
        else:
            lines.append('    {')
            lines += [f'        {b}' for b in body]
            lines.append('    }')
    lines.append('}')
    # every hand-off to the executor ends the function: a tail (cpu.h, #101)
    return [ln.replace('ct_interp_rest(cpu, s0);', 'ct_tail_rest(cpu, s0);') for ln in lines]


def emit_module(reg: funcs.Registry, metas: list[funcs.FuncMeta], module: str) -> tuple[str, str]:
    global _REG
    _REG = reg
    _EXTERNS.clear()
    _EXTERNS.update(reg.externs)
    sel = [fm for fm in metas if fm.module == module]
    if not sel:
        raise EmitError(f'no functions in module {module!r}')
    guard = f'CT_OUT_{module.upper()}_H'
    c = [HEADER, '#include "ops.h"', '#include "ct_funcs.h"', f'#include "{module}.h"', '']
    h = [HEADER, f'#ifndef {guard}', f'#define {guard}', '', '#include <stdint.h>', '',
         '#include "cpu.h"', '']
    table = []
    for fm in sel:
        for st in fm.entry_states():
            try:
                fn = reg.function(fm.addr, st)
            except DecodeError as ex:
                raise EmitError(f'{fm.name}: {ex}') from None
            c += emit_function(fm, fn) + ['']
            name = c_name(fm.addr, st)
            h.append(f'void {name}(CPU *cpu);  /* {fm.name} */')
            table.append(f'    {{"{fm.name}", 0x{fm.addr:06X}, "{st.tag()}", {fn.size}, {name}}},')
    h += ['', 'typedef struct {', '    const char *name;', '    uint32_t addr;',
          '    const char *state;', '    uint16_t size;', '    void (*fn)(CPU *);',
          f'}} ct_func_{module};', '',
          f'extern const ct_func_{module} {module}_funcs[];',
          f'extern const unsigned {module}_func_count;', '', '#endif', '']
    c += [f'const ct_func_{module} {module}_funcs[] = {{'] + table + ['};',
          f'const unsigned {module}_func_count = {len(table)};', '']
    return '\n'.join(c), '\n'.join(h)


def calls_extern(reg: funcs.Registry, addr: int, st: decode.State, memo: dict) -> bool:
    """Can (addr, st) reach an extern hook it would take even in the frame
    scheduler? Direct calls and jumps to a returning extern run the real
    code there (extern_call); a noreturn extern, or any extern in a jump
    table's case, still takes the hook, which stands in for ROM code the
    translation doesn't run, so a function that can reach one (directly or
    through its callees) is interpreted in system mode."""
    key = (addr,) + st.key()
    if key in memo:
        return memo[key]
    memo[key] = False   # a cycle adds nothing
    fn = reg.function(addr, st)
    edges = [(t, s) for t, s in fn.calls.values()] + [(t, s) for t, s in fn.tails.values()]
    edges += [(t, s) for ts, s in fn.tables.values() for t in ts]
    direct = [t for t, _ in list(fn.calls.values()) + list(fn.tails.values())]
    result = any(t in reg.externs for ts, _ in fn.tables.values() for t in ts) or \
        any(t in reg.externs and reg.externs[t].noreturn for t in direct) or any(
            calls_extern(reg, t, s, memo) for t, s in edges if t not in reg.externs)
    memo[key] = result
    return result


def emit_prototypes(reg: funcs.Registry, metas: list[funcs.FuncMeta]) -> tuple[str, str]:
    """ct_funcs.h (all prototypes) and ct_funcs.c (the tables declared in
    runtime/func_table.h)."""
    h = [HEADER, '#ifndef CT_OUT_FUNCS_H', '#define CT_OUT_FUNCS_H', '', '#include <stdint.h>', '',
         '#include "cpu.h"', '#include "func_table.h"', '']
    c = [HEADER, '#include "ct_funcs.h"', '', 'const ct_func ct_funcs[] = {']
    n = 0
    for fm in metas:
        for st in fm.entry_states():
            name = c_name(fm.addr, st)
            fn = reg.function(fm.addr, st)
            h.append(f'void {name}(CPU *cpu);  /* {fm.name} */')
            db = fm.db if fm.db is not None else -1
            dp = fm.dp if fm.dp is not None else -1
            ext = int(takes_hook(fn, reg.externs))
            c.append(f'    {{"{fm.name}", 0x{fm.addr:06X}, {int(st.m)}, {int(st.x)}, {fn.size}, '
                     f'{db}, {dp}, {ext}, {name}}},')
            n += 1
    h += ['', '#endif', '']
    c += ['};', f'const unsigned ct_func_count = {n};', '']
    jt = sorted(reg.jumptables.items())
    ex = sorted(reg.externs.values(), key=lambda e: e.addr)
    for e in ex:
        h.insert(h.index('#include "func_table.h"') + 2,
                 f'void ct_hook_{e.hook}(CPU *cpu);  /* extern {e.name} ${e.addr:06X} ({e.kind}) */')
    c += ['const ct_extern ct_externs[] = {']
    kinds = {'JSR': 0, 'JSL': 1, 'JML': 2}
    c += [f'    {{0x{e.addr:06X}, {kinds[e.kind]}, ct_hook_{e.hook}}},' for e in ex] or \
         ['    {0, 0, 0},']
    c += ['};', f'const unsigned ct_extern_count = {len(ex)};', '']
    c += ['const ct_jumptable ct_jumptables[] = {']
    c += [f'    {{0x{site:06X}, {count}}},' for site, count in jt] or ['    {0, 0},']
    c += ['};', f'const unsigned ct_jumptable_count = {len(jt)};', '']
    return '\n'.join(h), '\n'.join(c)


def fnv64(data: bytes) -> int:
    h = 0xCBF29CE484222325
    for b in data:
        h = ((h ^ b) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def emit_overlays(reg: funcs.Registry, manifest: str | None) -> tuple[str, list[str]]:
    """ct_overlays.c: code the game puts in WRAM (#92), recompiled from the
    images a game build step wrote (manifest: [[overlay]] name, dst, image,
    [[overlay.entry]] addr, states). Each entry is decoded from its image
    (calls into ROM compile as usual; anything else in WRAM is an interpreter
    call) and kept only if it decodes, emits, and stays inside the image.
    The table records the WRAM bytes each function was decoded from and
    their FNV-1a 64 hash: the runtime runs it only while they still match.
    Returns the source and the entries left out, with why."""
    global _OVERLAY, _REG
    _REG = reg
    overlays = []
    if manifest:
        with open(manifest, 'rb') as f:
            overlays = tomllib.load(f).get('overlay', [])
    c = [HEADER, '#include "ops.h"', '#include "overlay.h"', '#include "ct_funcs.h"', '']
    table, skipped = [], []
    _EXTERNS.clear()
    _EXTERNS.update(reg.externs)
    for ov in overlays:
        data = open(ov['image'], 'rb').read()
        base = ov['dst']
        img = f'img_{ov["name"]}'
        c += [f'static const uint8_t {img}[{len(data)}] = {{'] + \
             ['    ' + ', '.join(f'0x{b:02X}' for b in data[k:k + 16]) + ','
              for k in range(0, len(data), 16)] + ['};', '']
        image = decode.Image(reg.rom, base, data)
        _OVERLAY = ov['name']
        try:
            for e in ov.get('entry', []):
                for tag in e['states']:
                    st = decode.parse_state(tag)
                    fm = funcs.FuncMeta(f'{ov["name"]}_{e["addr"]:06X}', e['addr'], (tag,), 0,
                                        None, None, 'overlays')
                    try:
                        fn = decode.decode_function(image, e['addr'], st, reg)
                        lo, hi = fn.extent()
                        if any(not base <= i.addr < base + len(data) for i in fn.insns):
                            raise EmitError('runs outside its image')
                        if takes_hook(fn, reg.externs):   # see calls_extern
                            raise EmitError('takes a hook that stands in for code')
                        body = emit_function(fm, fn)
                    except (DecodeError, EmitError) as ex:
                        skipped.append(f'{fm.name} {tag}: {ex}')
                        continue
                    # handing its rest to the interpreter ends its own code
                    c += [ln.replace('ct_tail_rest(', 'ct_overlay_tail_rest(') for ln in body] + ['']
                    name = c_name(e['addr'], st)
                    h = fnv64(data[lo - base:hi - base + 1])
                    table.append(f'    {{"{fm.name}", 0x{e["addr"]:06X}, {int(st.m)}, {int(st.x)}, '
                                 f'0x{lo:06X}, 0x{hi:06X}, 0x{h:016X}ull, {name}, {img}, '
                                 f'0x{base:06X}, {len(data)}}},')
        finally:
            _OVERLAY = ''
    c += ['const ct_overlay_func ct_overlay_funcs[] = {'] + \
         (table or ['    {0, 0, 0, 0, 0, 0, 0, 0},']) + \
         ['};', f'const unsigned ct_overlay_func_count = {len(table)};', '']
    return '\n'.join(c), skipped


def modules(metas: list[funcs.FuncMeta]) -> list[str]:
    return sorted({fm.module for fm in metas})


def write_if_changed(path: str, text: str) -> None:
    if os.path.isfile(path):
        with open(path) as f:
            if f.read() == text:
                return
    with open(path, 'w') as f:
        f.write(text)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--module', help='emit one module (default: all)')
    ap.add_argument('--list-modules', action='store_true')
    ap.add_argument('--out', help='output directory (required unless --list-modules)')
    ap.add_argument('--rom')
    ap.add_argument('--funcs', required=True, help="the game's funcs.toml")
    ap.add_argument('--overlays', help='manifest of WRAM code images to recompile (#92)')
    a = ap.parse_args(argv)
    metas = funcs.load(a.funcs)
    if a.list_modules:
        print(';'.join(modules(metas)))
        return 0
    if not a.out:
        ap.error('--out is required')
    reg = funcs.Registry(decode.load_rom(a.rom), metas, a.funcs)
    metas, pending = funcs.split_emittable(reg, metas)
    for fm, why in pending:
        print(f'emit: manual root {fm.name} ${fm.addr:06X} not emitted yet: {why}', file=sys.stderr)
    os.makedirs(a.out, exist_ok=True)
    for mod in [a.module] if a.module else modules(metas):
        src, hdr = emit_module(reg, metas, mod)
        write_if_changed(os.path.join(a.out, f'{mod}.c'), src)
        write_if_changed(os.path.join(a.out, f'{mod}.h'), hdr)
    hdr, tab = emit_prototypes(reg, metas)
    write_if_changed(os.path.join(a.out, 'ct_funcs.h'), hdr)
    write_if_changed(os.path.join(a.out, 'ct_funcs.c'), tab)
    src, skipped = emit_overlays(reg, a.overlays)
    for why in skipped:
        print(f'emit: overlay entry left to the interpreter: {why}', file=sys.stderr)
    write_if_changed(os.path.join(a.out, 'ct_overlays.c'), src)
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1:]))
    except (DecodeError, EmitError) as ex:
        print(f'emit: {ex}', file=sys.stderr)
        sys.exit(1)
